const analogies = [

    {
      quote: "婚姻是一座围城，城外的人想进去，城里的人想出来。",
      source: "钱锺书《围城》",
      type: "人生哲理",
      concept: "婚姻的本质困境",
      interpretation: "用「围城」这一具象建筑比喻婚姻的悖论性——拥有即渴望逃离，缺失即渴望拥有",
      alsoUse: "职业选择、移民抉择、任何「这边望着那边好」的人生处境",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "人生天地之间，若白驹之过隙，忽然而已。",
      source: "《庄子·知北游》",
      type: "人生哲理",
      concept: "生命短暂",
      interpretation: "以白马掠过缝隙的瞬间画面烘托人生须臾，画面感极强",
      alsoUse: "时间管理、珍惜当下、告别拖延",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "人生如逆旅，我亦是行人。",
      source: "苏轼《临江仙》",
      type: "人生哲理",
      concept: "人生旅途的过客感",
      interpretation: "将人生比为客栈，每个人都是匆匆旅客——豁达中带苍凉",
      alsoUse: "面对挫折、离别赠言、人生阶段的切换",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "生活就是个缓慢受锤的过程，人一天天老下去，奢望也一天天消失，最后变得像挨了锤的牛一样。",
      source: "王小波《黄金时代》",
      type: "人生哲理",
      concept: "生活对人的消磨",
      interpretation: "以「受锤的牛」比喻被生活反复捶打后逐渐麻木的人，粗粝而准确",
      alsoUse: "职场倦怠、中年危机、理想主义褪色",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "时间就像海绵里的水，只要愿挤，总还是有的。",
      source: "鲁迅",
      type: "人生哲理",
      concept: "时间管理",
      interpretation: "将抽象的时间比作海绵中的水，强调人的主观能动性可以挤出时间",
      alsoUse: "学习规划、效率提升、碎片时间利用",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "世上本没有路，走的人多了，也便成了路。",
      source: "鲁迅《故乡》",
      type: "人生哲理",
      concept: "开拓与创新的本质",
      interpretation: "用最朴素的「路」比喻所有曾被开创的事业——先驱者踏出第一步",
      alsoUse: "创业、创新、社会变革、个人突破",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "All the world's a stage, and all the men and women merely players.",
      source: "Shakespeare, As You Like It",
      type: "人生哲理",
      concept: "人生如戏",
      interpretation: "将世界比作舞台、人比作演员，揭示社会角色的表演性本质",
      alsoUse: "职场角色切换、身份认同、社会学讨论",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "你们是早晨八九点钟的太阳，希望寄托在你们身上。",
      source: "毛泽东",
      type: "人生哲理",
      concept: "青年与希望",
      interpretation: "以初升太阳比喻青年人的朝气与无限可能，意象光明温暖",
      alsoUse: "开学演讲、团队新人激励、代际传承",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "治大国若烹小鲜。",
      source: "《道德经》第六十章",
      type: "治理管理",
      concept: "治理的尺度感",
      interpretation: "煎小鱼不能频繁翻动——治理大国同样不该朝令夕改、过度干预",
      alsoUse: "企业管理、政策制定、家庭管理、项目管理",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "摸着石头过河。",
      source: "陈云（后用于改革开放语境）",
      type: "治理管理",
      concept: "渐进式改革方法论",
      interpretation: "以涉水过河的谨慎姿态比喻在未知领域中步步为营的试探性策略",
      alsoUse: "创业试错、产品MVP验证、个人转行",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "上善若水。水善利万物而不争，处众人之所恶，故几于道。",
      source: "《道德经》第八章",
      type: "治理管理",
      concept: "柔性领导力",
      interpretation: "以水的至柔至韧比喻最高境界的领导者——利他、谦下、包容",
      alsoUse: "管理哲学、谈判策略、人际冲突化解",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "天下事当于大处着眼，小处下手。",
      source: "曾国藩",
      type: "治理管理",
      concept: "战略与执行的统一",
      interpretation: "以「眼」与「手」的不同功能类比战略格局与落地执行的二元统一",
      alsoUse: "项目管理、年度规划、个人目标拆解",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "一只狮子率领的羊群，能打败一只羊率领的狮群。",
      source: "拿破仑（传）",
      type: "治理管理",
      concept: "领导力的决定性作用",
      interpretation: "以动物强弱反转的设定比喻优秀领导者对团队战斗力的乘数效应",
      alsoUse: "招聘CEO、团队重组、组织变革",
      lang: "中文译",
      date: "2026-05-25",
    },
    {
      quote: "If the only tool you have is a hammer, you tend to see every problem as a nail.",
      source: "Abraham Maslow",
      type: "治理管理",
      concept: "思维模型的局限性",
      interpretation: "以锤子和钉子比喻单一工具会导致认知窄化——需要多元思维模型",
      alsoUse: "跨学科学习、避免专业偏见、产品设计",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "Only when the tide goes out do you discover who's been swimming naked.",
      source: "Warren Buffett",
      type: "商业经济",
      concept: "风险暴露机制",
      interpretation: "以退潮后裸泳者暴露比喻市场下行时真正检验企业的抗风险能力",
      alsoUse: "经济周期分析、投资风控、创业公司压力测试",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "看不见的手。",
      source: "Adam Smith《国富论》",
      type: "商业经济",
      concept: "市场自发调节机制",
      interpretation: "以一只无形的「手」比喻市场中无数个体自利行为聚合产生的自组织秩序",
      alsoUse: "平台经济、价格机制解释、自由竞争理论",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "风口上，猪都能飞起来。",
      source: "雷军",
      type: "商业经济",
      concept: "趋势红利的力量",
      interpretation: "以「猪飞」这一荒谬画面极致化地说明顺势而为远大于个人努力",
      alsoUse: "创业选赛道、投资择时、职业规划",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "鱼和熊掌不可兼得。",
      source: "《孟子·告子上》",
      type: "商业经济",
      concept: "取舍与机会成本",
      interpretation: "以两种美味不可同时拥有比喻资源约束下的选择困境——经济学核心",
      alsoUse: "预算分配、时间管理、战略聚焦",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "不要把所有的鸡蛋放在同一个篮子里。",
      source: "西方谚语",
      type: "商业经济",
      concept: "风险分散原则",
      interpretation: "以鸡蛋易碎的属性比喻资产集中带来的系统性风险",
      alsoUse: "投资组合、供应链多元化、收入来源多样化",
      lang: "中文译",
      date: "2026-05-25",
    },
    {
      quote: "雪球效应。",
      source: "Warren Buffett",
      type: "商业经济",
      concept: "复利增长",
      interpretation: "以滚雪球比喻复利效应——长坡厚雪、越滚越大",
      alsoUse: "知识积累、品牌建设、用户增长",
      lang: "中文译",
      date: "2026-05-25",
    },
    {
      quote: "黑天鹅。",
      source: "Nassim Nicholas Taleb《黑天鹅》",
      type: "商业经济",
      concept: "极端不可预测事件",
      interpretation: "以欧洲人发现黑天鹅(此前以为天鹅皆白)比喻颠覆性小概率事件的冲击",
      alsoUse: "风险管理、疫情应对、地缘政治分析",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "电脑是人类大脑的自行车。",
      source: "Steve Jobs",
      type: "科技创新",
      concept: "工具增强人类能力",
      interpretation: "以自行车放大人类移动效率来类比电脑对思维效率的倍增作用",
      alsoUse: "AI工具、效率软件、可穿戴设备的推广话术",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "如果我看得更远，那是因为站在巨人的肩膀上。",
      source: "Isaac Newton",
      type: "科技创新",
      concept: "知识传承与创新",
      interpretation: "以物理叠加画面比喻学术进步建立在先行者积累之上",
      alsoUse: "论文引言、产品迭代、师徒制教育",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "给岁月以文明，而不是给文明以岁月。",
      source: "刘慈欣《三体》",
      type: "科技创新",
      concept: "文明的真正价值",
      interpretation: "以「岁月」与「文明」的主客位置互换，类比质重于量的价值判断",
      alsoUse: "产品哲学、生命意义、可持续发展讨论",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "数据是新的石油。",
      source: "Clive Humby (2006)",
      type: "科技创新",
      concept: "数据的战略价值",
      interpretation: "将数据比作石油——未经提炼则价值有限，精炼后驱动世界",
      alsoUse: "数字化转型、数据治理、AI训练数据",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "媒介即讯息。",
      source: "Marshall McLuhan",
      type: "科技创新",
      concept: "媒介本身决定内容形态",
      interpretation: "以「媒介=讯息」这个等式类比传播载体会深层重塑人类认知模式",
      alsoUse: "短视频vs长文对比、社交媒体的社会影响、教育媒介选择",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "学如逆水行舟，不进则退。",
      source: "《增广贤文》",
      type: "教育学习",
      concept: "持续学习的重要性",
      interpretation: "以逆水划船比喻学习——停止用力就会退步，画面感让劝学变得有力",
      alsoUse: "终身学习、技能保鲜、行业竞争",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "青，取之于蓝而青于蓝；冰，水为之而寒于水。",
      source: "荀子《劝学》",
      type: "教育学习",
      concept: "学习使人超越",
      interpretation: "以染料提取与冰水转化双线类比学生通过后天的学习可以超越老师",
      alsoUse: "师徒传承、企业培训、技术迭代",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "庖丁解牛，游刃有余。",
      source: "《庄子·养生主》",
      type: "教育学习",
      concept: "熟能生巧的境界",
      interpretation: "以解牛刀法的精准流畅比喻经过大量练习后对事物内在规律的通透掌握",
      alsoUse: "技能进阶、专业训练、流程优化",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "大智若愚，大巧若拙。",
      source: "《道德经》第四十五章",
      type: "教育学习",
      concept: "智慧的深层悖论",
      interpretation: "以「愚」与「拙」的表象反衬真正的智慧——肤浅的聪明反而外显",
      alsoUse: "面试识人、谦逊领导力、学术讨论",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "书山有路勤为径，学海无涯苦作舟。",
      source: "韩愈（传）",
      type: "教育学习",
      concept: "勤奋是学习的根本",
      interpretation: "以登山与渡海的双重意象将抽象的努力具象化为路径和舟船",
      alsoUse: "考试激励、知识管理、自我驱动",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "Education is not the filling of a pail, but the lighting of a fire.",
      source: "W.B. Yeats",
      type: "教育学习",
      concept: "教育的本质",
      interpretation: "以「灌水桶」与「点火把」二元类比区分填鸭式教学和启发式教育",
      alsoUse: "课程设计、家庭教育、企业内训",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "登山则情满于山，观海则意溢于海。",
      source: "刘勰《文心雕龙·神思》",
      type: "文学艺术",
      concept: "创作者的情感投射",
      interpretation: "以登山观海时情感与自然的交融比喻作家创作时的全身心沉浸状态",
      alsoUse: "艺术创作、情感沉浸、场景描写技法",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "昨夜西风凋碧树。独上高楼，望尽天涯路。",
      source: "王国维《人间词话》（一境）",
      type: "文学艺术",
      concept: "求索的第一重境界",
      interpretation: "以萧瑟独立的高楼远望画面比喻成大事者最初的孤独求索",
      alsoUse: "创业初期、研究选题、人生方向的迷茫期",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "衣带渐宽终不悔，为伊消得人憔悴。",
      source: "王国维《人间词话》（二境）",
      type: "文学艺术",
      concept: "求索的第二重境界",
      interpretation: "以相思消瘦比喻对目标的全心投入——不计代价的执著追求",
      alsoUse: "创业坚持、学术深耕、技能打磨期",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "众里寻他千百度，蓦然回首，那人却在灯火阑珊处。",
      source: "王国维《人间词话》（三境）",
      type: "文学艺术",
      concept: "求索的第三重境界",
      interpretation: "以蓦然回首的顿悟画面比喻量变积累之后的质变——灵感不期而至",
      alsoUse: "产品突破、科学发现、豁然开朗的人生顿悟",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "A great novel is a pocket theater.",
      source: "Somerset Maugham",
      type: "文学艺术",
      concept: "小说的本质",
      interpretation: "将小说比作「口袋里的剧场」，精准捕捉文字的戏剧张力和便携性",
      alsoUse: "影视改编、沉浸式阅读推广、内容创作",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "人是万物的尺度。",
      source: "普罗泰戈拉（Protagoras）",
      type: "哲学思辨",
      concept: "相对主义认识论",
      interpretation: "以「尺度」比喻人的主观感知是判断一切的基准——主体性宣言",
      alsoUse: "用户体验设计、认知偏见讨论、文化相对主义",
      lang: "古希腊译",
      date: "2026-05-25",
    },
    {
      quote: "洞穴比喻。",
      source: "Plato《理想国》",
      type: "哲学思辨",
      concept: "认知的局限与启蒙",
      interpretation: "以囚徒看洞壁影子的设定比喻人类被感官和偏见囚禁的认知困境",
      alsoUse: "信息茧房、真相追求、科学启蒙",
      lang: "古希腊译",
      date: "2026-05-25",
    },
    {
      quote: "人是会思想的芦苇。",
      source: "Pascal《思想录》",
      type: "哲学思辨",
      concept: "人的脆弱与高贵",
      interpretation: "以「芦苇」的脆弱和「思想」的伟大并置——人是宇宙中最脆弱的强者",
      alsoUse: "存在主义讨论、生命教育、面对挫折的心态",
      lang: "法文译",
      date: "2026-05-25",
    },
    {
      quote: "上帝不掷骰子。",
      source: "Albert Einstein",
      type: "自然宇宙",
      concept: "对量子力学随机性的质疑",
      interpretation: "以掷骰子比喻随机性——爱因斯坦坚持宇宙存在确定性的因果律",
      alsoUse: "科学与哲学辩论、不确定性管理、概率思维",
      lang: "德文译",
      date: "2026-05-25",
    },
    {
      quote: "We are made of star-stuff. 我们是星尘。",
      source: "Carl Sagan",
      type: "自然宇宙",
      concept: "人与宇宙的联系",
      interpretation: "以星际物质的转化比喻人类的身体元素来自恒星核聚变——科学中见诗意",
      alsoUse: "科普写作、宇宙观教育、环保意识",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "蝴蝶效应。",
      source: "Edward Lorenz",
      type: "自然宇宙",
      concept: "混沌系统的敏感性",
      interpretation: "以蝴蝶扇翅引发飓风比喻微小初始条件变化如何通过非线性放大产生巨大后果",
      alsoUse: "社会运动、市场波动、项目管理中的小疏忽",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "生命之树。",
      source: "Charles Darwin",
      type: "自然宇宙",
      concept: "物种演化关系",
      interpretation: "以树的枝干分叉比喻生物由共同祖先不断分化的演化历程",
      alsoUse: "分类学、知识图谱、组织架构演化",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "天行健，君子以自强不息。",
      source: "《周易·乾卦》",
      type: "自然宇宙",
      concept: "自强精神",
      interpretation: "以天体的永恒运转比喻君子应当效法天的刚健不息",
      alsoUse: "企业文化、创业精神、逆境应对",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "如人饮水，冷暖自知。",
      source: "《景德传灯录》（禅宗）",
      type: "人际情感",
      concept: "主体体验的不可替代性",
      interpretation: "以饮水的冷暖感受比喻只有当事人才能真正体会个中滋味",
      alsoUse: "理解他人困境、共情教育、亲密关系沟通",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "爱情像一只自由的鸟。",
      source: "比才歌剧《卡门》",
      type: "人际情感",
      concept: "爱情不可强求",
      interpretation: "以野生飞鸟比喻爱情——来去自由、不可驯服",
      alsoUse: "分手安慰、自由恋爱观、放下执念",
      lang: "法文译",
      date: "2026-05-25",
    },
    {
      quote: "心有猛虎，细嗅蔷薇。",
      source: "Siegfried Sassoon（余光中译）",
      type: "人际情感",
      concept: "刚柔并济的人性",
      interpretation: "以猛虎与蔷薇的极致对比比喻人心中力量与温柔可以共存",
      alsoUse: "领导力风格、性别气质讨论、人物塑造",
      lang: "英文译",
      date: "2026-05-25",
    },
    {
      quote: "君子之交淡如水，小人之交甘若醴。",
      source: "《庄子·山木》",
      type: "人际情感",
      concept: "友谊的境界层级",
      interpretation: "以水与甜酒的口感差异比喻真正长久的友谊不需要刻意甜蜜",
      alsoUse: "社交关系维护、职场人脉、识人交友",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "No man is an island, entire of itself.",
      source: "John Donne",
      type: "人际情感",
      concept: "人的社会性",
      interpretation: "以孤岛比喻脱离群体的人——人类天生互联、荣辱与共",
      alsoUse: "团队建设、社群运营、全球化的哲学基础",
      lang: "英文",
      date: "2026-05-25",
    },
    {
      quote: "人生就像骑自行车，要保持平衡就必须不断前进。\nLife is like riding a bicycle. To keep your balance, you must keep moving.",
      source: "阿尔伯特·爱因斯坦（Albert Einstein）",
      type: "人生哲理",
      concept: "人生动力与平衡的关系",
      interpretation: "将保持人生平衡这一抽象概念比作骑车的物理体验，以人人都懂的日常经验诠释深刻的人生智慧。妙在简洁——骑车不前进就会倒，人生亦如此。",
      alsoUse: "职业发展规划、创业指导、面对中年危机的自我激励",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "愤怒就像握着一块热炭想要扔向别人，但被烫伤的是你自己。\nAnger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.",
      source: "佛陀（佛教经典）",
      type: "人生哲理",
      concept: "愤怒情绪的本质",
      interpretation: "这个类比极其直观地揭示了愤怒的自我伤害本质。画面感极强——手持热炭的场景令人本能地感到灼痛，精准传达了『愤怒首先伤害自己』的东方智慧。",
      alsoUse: "情绪管理培训、人际关系辅导、领导力培养",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "思想就像降落伞，不打开就无法发挥作用。\nA mind is like a parachute. It doesn’t work if it is not open.",
      source: "弗兰克·扎帕（Frank Zappa）",
      type: "教育学习",
      concept: "开放思维的重要性",
      interpretation: "降落伞的『打开』与思想的『开放』形成精确映射——两者都关乎生存，且『不打开就失效』的逻辑高度一致，幽默而不可辩驳。",
      alsoUse: "创新文化倡导、教育改革讨论、跨学科交流",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "钓鱼的第一条规则是在有鱼的地方钓鱼，第二条规则是记住第一条规则。投资也是如此。",
      source: "查理·芒格（Charlie Munger）",
      type: "商业经济",
      concept: "投资方向选择",
      interpretation: "用『钓鱼』这种极其朴素的日常活动类比投资——太多人在没有鱼的地方拼命撒网。这个类比的妙处在于它用最基本的常识击穿了一切复杂理论。",
      alsoUse: "职业选择、创业赛道选择、市场定位策略",
      lang: "ZH",
      date: "2026-05-25",
    },
    {
      quote: "笔胜于剑。\nThe pen is mightier than the sword.",
      source: "爱德华·布尔沃-李顿（Edward Bulwer-Lytton），戏剧《黎塞留》",
      type: "文学艺术",
      concept: "思想与文字的力量大于武力",
      interpretation: "西方文学中最著名的类比之一。将『笔』与『剑』并列，以小博大——一支轻笔竟比重剑更有力，精准传达了思想力量的不可战胜。",
      alsoUse: "外交谈判、新闻舆论力量论述、非暴力抗争理念",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "批评可能令人不悦，但它是必要的。批评对人体的作用，就如同疼痛对人体的作用——它提醒我们注意不健康的状态。\nCriticism may not be agreeable, but it is necessary. It fulfils the same function as pain in the human body. It calls attention to an unhealthy state of things.",
      source: "温斯顿·丘吉尔（Winston Churchill）",
      type: "治理管理",
      concept: "批评的价值与必要性",
      interpretation: "将批评比作身体的疼痛——虽令人不适，却是健康的\u201c警报系统\u201d。疼痛告诉你哪里出了问题，批评同样告诉组织或个人哪里需要改进。忽视批评如忽视疼痛，终将酿成大患。",
      alsoUse: "绩效考核反馈、团队建设、自我成长、舆论监督的价值论述",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "人们就像彩色玻璃窗。阳光灿烂时，它们闪闪发光；但当黑暗降临，唯有那些内心有光的人，才会显露出真正的美。\nPeople are like stained glass windows. They sparkle and shine when the sun is out, but when the darkness sets in, their true beauty is revealed only if there is a light from within.",
      source: "伊丽莎白·库伯勒-罗斯（Elisabeth Kübler-Ross），生死学大师",
      type: "人生哲理",
      concept: "逆境中的人性光辉",
      interpretation: "以彩色玻璃窗在不同光线下的呈现来类比人性——顺境中人人光彩照人，真正区分高下的是黑暗时刻。内心有光的人，在逆境中反而最耀眼。这个类比兼具诗意与洞察力。",
      alsoUse: "领导力论述、面试选拔、危机管理、人物评价",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "一本真正伟大的书，应在青年时读，中年时读，老年时再读——正如一座精美的建筑，应在晨光中、正午时、月光下分别观赏。\nA truly great book should be read in youth, again in maturity, and once more in old age, as a fine building should be seen by morning light, at noon, and by moonlight.",
      source: "罗伯逊·戴维斯（Robertson Davies），加拿大小说家",
      type: "教育学习",
      concept: "经典作品的多维重读价值",
      interpretation: "将书籍比作建筑、人生阶段比作光线——同一本书在不同人生阶段会呈现出截然不同的面貌，正如同一座建筑在晨光、正午、月光下各有其美。经典不是读一次就够的，而是需要一生的时间才能读完。",
      alsoUse: "阅读推广、教育理念阐述、读书会主题、终身学习倡导",
      lang: "EN/ZH",
      date: "2026-05-25",
    },
    {
      quote: "同一句格言，在一个饱经风霜、备受煎熬的老人嘴里说出来，和在一个天真可爱、未谙世事的孩子嘴里说出来，含义是根本不同的。",
      source: "黑格尔（G.W.F. Hegel），《小逻辑》",
      type: "哲学思辨",
      concept: "哲学理解与生命体验的关系",
      interpretation: "用同一个句子从不同人嘴里说出的差异，来类比哲学真理不能被简单背诵——它必须被'活过'。老人说出的格言背负着一生的重量，孩子说出的只是词语。这个类比揭示了：真正的理解不等于记住，而等于经历。",
      alsoUse: "教育理念、领导力培养、经验传承、读书方法论",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "卖止痛药永远比卖维生素容易。止痛药解决的是'没有不行'的痛点，维生素解决的是'有了更好'的痒点。",
      source: "硅谷创业圈流行类比，源自产品设计经典《上瘾》（Hooked）及相关论述",
      type: "商业经济",
      concept: "产品定位的痛点vs痒点策略",
      interpretation: "以药品品类来类比产品定位策略——止痛药对应刚需，用户会主动寻找；维生素对应锦上添花，需要大量教育市场。这个类比简洁有力地解释了为什么有些产品不推自火，有些产品砸钱也推不动。",
      alsoUse: "创业BP撰写、产品需求分析、市场营销策略、投资判断",
      lang: "中文",
      date: "2026-05-25",
    },
    {
      quote: "类比，说到底，什么也决定不了，但它能让人有“宾至如归”之感。\nAnalogies, it is true, decide nothing, but they can make one feel more at home.",
      source: "西格蒙德·弗洛伊德（Sigmund Freud），《精神分析新论》（1933）",
      type: "哲学思辨",
      concept: "类比的功能与边界",
      interpretation: "这句话同时道出了类比的两面：它无法作为逻辑证明（决定不了任何事），但却能让人在陌生的理论中找到熟悉感与归属感——这正是科普写作的核心价値所在。弗洛伊德以极简洁的语言划定了类比思维的入门资格证书与局限性警示。",
      alsoUse: "科普写作方法论、教学设计、词典工具类型定位",
      lang: "EN/ZH",
      date: "2026-05-27",
    },
    {
      quote: "我常常用象棋比喻：一个人可以学会象棋的全部规则，但这不意味着他就能下得好棋。物理学的现状就好比：我们已经掌握了象棋的大部分规则，但这个局尚有一两个规则我们还不知道。\nI often use the analogy of a chess game: one can learn all the rules of chess, but one doesn't know how to play well. The present situation in physics is as if we know chess, but we don't know one or two rules.",
      source: "理查德·费曼（Richard P. Feynman），引自《超弦：万物理论？》（1988）",
      type: "科技创新",
      concept: "科学知识的不完整性",
      interpretation: "象棋规则已知却下不好棋，这个妙喜类比把物理学的处境转化为直观知觉：我们已掌握的知识不是问题，问题在于那“一两条未知的规则”。费曼常用具体类比把复杂理论坐实，是科普大师的标志性风格。",
      alsoUse: "科学研究方向论证、认知局限性讲解、局部知识与全局推断的区别",
      lang: "EN/ZH",
      date: "2026-05-27",
    },
    {
      quote: "发明家不可或缺的能力，是能发现类比的逻辑思维。不！不是数学思维。一个有数学头脑的人从未发明过什么重要的东西。\nAn essential [of an inventor] is a logical mind that sees analogies. No! Not mathematical. No man of a mathematical habit of mind ever invented anything that amounted to much.",
      source: "托马斯·爱迪生（Thomas Edison），引自《世界工作与娱乐》（1905）",
      type: "科技创新",
      concept: "创新思维的真正源泉",
      interpretation: "爱迪生此处颠覆常识：人们以为发明需要数学头脑，他却说核心资质是'能发现类比的逻辑思维'。这个判断来自一个一生拥有数千项专利的实践者，比任何理论更具说服力。它提醒我们：思维过于精确反而抓不到实质。",
      alsoUse: "创新驱动力讨论、跨学科思维训练、发明家精神演讲",
      lang: "EN/ZH",
      date: "2026-05-27",
    },
    {
      quote: "这个世界充满了希望的类比，和外表好看却令人疑惑的蛋，统称为可能性。\nThe world is full of hopeful analogies and handsome, dubious eggs, called possibilities.",
      source: "乔治·艾略特（George Eliot），英国小说家",
      type: "人生哲理",
      concept: "希望与不确定性的共存",
      interpretation: "\u201C充满希望的类比\u201D与\u201C外表好看却令人疑惑的蛋\u201D两个意象并列，深刻揭示了人类面对希望的矛盾心态：我们渴望希望，却清楚最美的蛋也可能内部腐烂。艾略特以这个类比同时摒弃盲目乐观与虚无主义，引导我们直面问题本身。",
      alsoUse: "风险管理讨论、创业项目评估、人生哲学思考",
      lang: "EN/ZH",
      date: "2026-05-27",
    },
    {
      quote: "青，取之于蓝，而青于蓝；冰，水为之，而寒于水。",
      source: "荀子《劝学》",
      type: "教育学习",
      concept: "后辈超越前辈的可能性",
      interpretation: "荀子以染料提取与冰水转化两条路径并列设喻，双线对举地说明：为什么不能承认学生超过老师的可能？这个类比自然瓦解了\u201C学生不如师\u201D的借口，同时将教学传承转化为一种自然现象——让论证本身成为类比的胜利。",
      alsoUse: "师徒传承、代际超越关系讨论、人才培育与个人成长",
      lang: "中文",
      date: "2026-05-27",
    },
    {
      quote: "流言这东西，比流感蔓延的速度更快，比流星所蕴含的能量更巨大，比流氓更具有恶意，比流产更能让人心力交瘁。",
      source: "钱钟书《围城》",
      type: "人际情感",
      concept: "舆论与语言的杀伤力",
      interpretation: "连续以“流”字开头的四个意象——流感、流星、流氓、流产——逐层递进，将抽象的流言杀伤力转化为可感的生理体验。妙在四个比喻共用同一前缀，以同音构建语义的倍增效应，堪称汉语修辞的极致示范。",
      alsoUse: "危机公关、社交媒体舆论管理、人际沟通培训",
      lang: "中文",
      date: "2026-05-26",
    },
    {
      quote: "心灵如同一座冰山，只有八分之一浮现在水面上，大部分隐藏在我们的潜意识之中。\nThe mind is like an iceberg; it floats with one-seventh of its bulk above water.",
      source: "西格蒙德·弗洛伊德（Sigmund Freud），精神分析学创始人",
      type: "哲学思辨",
      concept: "潜意识的巨大影响力",
      interpretation: "以冰山的水上/水下比例（1:7）精准类比意识与潜意识的关系——日常意识和理性只是表象，真正驱动行为的是那看不见的、庞大的潜意识。这个类比让精神分析学有了一个直观的视觉模型。",
      alsoUse: "心理学普及、用户行为分析、品牌营销中的潜意识影响",
      lang: "EN/ZH",
      date: "2026-05-26",
    },
    {
      quote: "科学是在黑暗中点燃的一支蜡烛，它不是答案的全部，但它是我们唯一的照明工具。\nScience is a candle in the dark.",
      source: "卡尔·萨根（Carl Sagan），《魔鬼出没的世界》",
      type: "科技创新",
      concept: "科学的有限性与不可替代性",
      interpretation: "萨根以“黑暗中的蜡烛”既承认科学照明范围的有限（不能照亮宇宙一切真相），又肯定其不可替代（唯有它能驱散无知的黑暗）。这个类比同时击中了科学主义者的傲慢与反智主义者的偏见。",
      alsoUse: "科技政策论证、科学科普写作、反伪科学论述",
      lang: "EN/ZH",
      date: "2026-05-26",
    },
    {
      quote: "时间是窃取青春的小偷。\nTime is a thief of youth.",
      source: "马克·吐温（Mark Twain），美国作家",
      type: "人生哲理",
      concept: "时间流逝的不可逆转性",
      interpretation: "拟人化的小偷赋予时间一种狡猾的主动性——它在人不知不觉中偷走最宝贵的青春，等你发现时为时已晚。这个类比远比“光阴似箭”更令人心惊，因为它暗示了我们是被动的受害者，而时间是主动的偷窃者。",
      alsoUse: "时间管理培训、人生规划、珍惜当下主题写作",
      lang: "EN/ZH",
      date: "2026-05-26",
    },
    {
      quote: "这欢喜是空的，像小孩子放的气球，上去不到几尺，便爆裂归于乌有，只留下忽忽若失的无名怅惘。",
      source: "钱钟书《围城》",
      type: "人生哲理",
      concept: "快乐的虚幻本质",
      interpretation: "以孩童吹胀的气球升空即破裂，类比许多人为之努力的人生喜悦——越是鼓吹越接近破灭，最终只剩怅惘。钱钟书以尖刻的幽默揭示了人类追逐快乐的荒诞性：我们精心充气的事物，本质不过是薄纸加一口气。",
      alsoUse: "消费主义批判、人生哲学讨论、反内卷论述",
      lang: "中文",
      date: "2026-05-26",
    },
    {
      quote: "也许每一个男子全都有过这样的两个女人，至少两个。娶了红玫瑰，久而久之，红的变了墙上的一抹蚊子血，白的还是\u201c床前明月光\u201d；娶了白玫瑰，白的便是衣服上沾的一粒饭粘子，红的却是心口上的一颗朱砂痣。",
      source: "张爱玲《红玫瑰与白玫瑰》",
      type: "人际情感",
      concept: "欲望与满足的永恒悖论",
      interpretation: "四重意象层层递进\u2014\u2014蚊子血对明月光、饭粘子对朱砂痣\u2014\u2014以极端反差揭示：得不到的永远在骚动，得到的永远在贬值。这个类比将人类欲望的悲剧结构视觉化为日常物件，每一重意象都比前一重更令人心惊。",
      alsoUse: "消费心理分析、职业倦怠、婚姻咨询",
      lang: "中文",
      date: "2026-05-27",
    },
    {
      quote: "我们把市场想象成两种海洋：红海代表所有现存的产业\u2014\u2014已知的市场空间，竞争规则已被划定；蓝海则代表所有今天还不存在的产业\u2014\u2014未知的市场空间，没有竞争者的染指。\nWe imagine two kinds of oceans: red oceans and blue oceans. Red oceans are all the industries in existence today\u2014the known market space. Blue oceans are all the industries not in existence today\u2014the unknown market space, untainted by competition.",
      source: "W. Chan Kim & Ren\u00e9e Mauborgne\u300a蓝海战略\u300b",
      type: "商业经济",
      concept: "从零和竞争到开创全新市场",
      interpretation: "以水的颜色纯粹化两种战略前景\u2014\u2014红海因血腥搏杀而染色，蓝海因无人涉足而澄澈\u2014\u2014这个类比将一个复杂的战略抉择瞬间坍缩为直观的视觉选择。",
      alsoUse: "创业赛道选择、职业规划、产品差异化",
      lang: "EN/ZH",
      date: "2026-05-27",
    },
    {
      quote: "但是太阳，它每时每刻都是夕阳也都是旭日。当它熄灭着走下山去收尽苍凉残照之际，正是它在另一面燃烧着爬上山巅布散烈烈朝辉之时。",
      source: "史铁生《我与地坛》",
      type: "人生哲理",
      concept: "结束与开始的同一性",
      interpretation: "以太阳在地球两个半球的同构性\u2014\u2014此处日落=彼处日出\u2014\u2014随喻死亡与新生的深层统一。史铁生在轮椅上看见的这个宇宙真理既冰冷又温暖，最终指向一种超脱：个体的结束不过是大尺度循环中的一个相位转换。",
      alsoUse: "生命教育、临终关怀、代际传承叙事",
      lang: "中文",
      date: "2026-05-27",
    },
    {
      quote: "井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也；曲士不可以语于道者，束于教也。",
      source: "《庄子·秋水》",
      type: "哲学思辨",
      concept: "认知边界的三重限制",
      interpretation: "以三种无法跨越自身环境界限的生物层层递进\u2014\u2014空间限制了井蛙、时间限制了夏虫、教条限制了固执之人\u2014\u2014但最终落点是启发而非指责：承认认知的有限性，才是真正对话的开始。",
      alsoUse: "跨文化交流、教育理念、破除信息茧房",
      lang: "中文",
      date: "2026-05-27",
    },
    {
      quote: "诸神处罚西西弗斯把一块巨石推上山顶，而石头因其自身重量一次次滚落。诸神认为，没有比无用且无望的劳动更可怕的惩罚了。\nThe gods had condemned Sisyphus to ceaselessly rolling a rock to the top of a mountain, whence the stone would fall back of its own weight. They had thought with some reason that there is no more dreadful punishment than futile and hopeless labor.",
      source: "阿尔贝·加缪（Albert Camus）《西西弗神话》",
      type: "哲学思辨",
      concept: "荒诞人生的价值重估",
      interpretation: "西西弗斯推石至今是西方世界最著名的哲学类比\u2014\u2014日复一日重返原点的徒劳\u2014\u2014但加缪在终点反转：\u201c我们必须想象西西弗斯是幸福的。\u201d这一翻转赋予荒诞以尊严：既然虚无不可逃避，人的反抗本身即是意义的来源。",
      alsoUse: "职场倦怠疗愈、创业坚持叙事、面对不确定性的心态建设",
      lang: "EN/ZH",
      date: "2026-05-27",
    },

    {
      quote: "人不能两次踏入同一条河流。\nNo man ever steps in the same river twice, for it’s not the same river and he’s not the same man.",
      source: "赫拉克利特（Heraclitus），古希腊哲学家",
      type: "哲学思辨",
      concept: "万物的永恒流动",
      interpretation: "以踏入流河的日常经验比喻宇宙的根本本质——没有任何东西是静止的，一切皆在流变之中。这是哲学史上最古老也最强大的类比之一，以水的流动象征时间、变化和生命本身。",
      alsoUse: "变革管理、个人成长、市场变化分析、“唯一不变的是变化”论述",
      lang: "EN/ZH",
      date: "2026-06-01",
    },
    {
      quote: "与恶龙缠斗过久，自身亦成恶龙；凝视深渊过久，深渊将回以凝视。\nHe who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.",
      source: "弗里德里希·尼采（Friedrich Nietzsche），《善恶的彼岸》第146节",
      type: "哲学思辨",
      concept: "与邪恶抵抗时自我异化的危险",
      interpretation: "怒龙与深渊双重意象构建了一个惊心动魄的警告：反抗恶的过程本身可能让你变成恶。这不是叫人放弃抵抗，而是提醒人们在斗争中保持自我反省——你的敌人正在塑造你。",
      alsoUse: "互联网自媒体讨论、网络暴力反思、商业竞争伦理、社会运动策略",
      lang: "EN/ZH",
      date: "2026-06-01",
    },
    {
      quote: "林中有两条路，我选择了人迹更少的那一条，从此一切都不同了。\nTwo roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.",
      source: "罗伯特·弗罗斯特（Robert Frost），《未选择的路》",
      type: "人生哲理",
      concept: "人生选择的不可逆转性",
      interpretation: "以林中叉路比喻人生的关键抉择——每次选择都是不可逆的，而正是这些选择构成了你独特的人生。诗人以最平常的自然场景承载了最深刻的人生哲学，成为英语世界被引用最多的诗歌之一。",
      alsoUse: "职业规划、创业决策、毕业典礼演讲、人生回顾",
      lang: "EN/ZH",
      date: "2026-06-01",
    },
    {
      quote: "月光照在路上，像是撒满了盐。",
      source: "余华《活着》",
      type: "文学艺术",
      concept: "悲伤的视觉化表达",
      interpretation: "用“撒满了盐”比喻月光——盐既白且刺痛，形象地传递了悲伤既纯净又灼痛的双重特质。仅七个字，将抽象的痛苦转化为可触可感的视觉意象，是中文现当代文学中最简洁有力的比喻之一。",
      alsoUse: "悲伤辅导、创作写作教学、情感表达训练",
      lang: "中文",
      date: "2026-06-01",
    },
    {
      quote: "爱上一个人，就好像创造了一种信仰，伺奉着一个随时会陨落的神。\nTo fall in love is to create a religion that has a fallible god.",
      source: "豪尔赫·路易斯·博尔赫斯（Jorge Luis Borges），阿根廷作家",
      type: "人际情感",
      concept: "爱情中理想与现实的张力",
      interpretation: "将恋爱比作宗教信仰，爱人比作“随时会陨落的神”——这个双重类比精准捉住了爱情的本质：它是一种非理性的奉献，但奉献的对象却只是凡人。博尔赫斯以一句话解构了所有浪漫关系的悲剧性。",
      alsoUse: "恋爱咨询、情感教育、人性讨论、偶像文化批判",
      lang: "EN/ZH",
      date: "2026-06-01",
    },
    {
      quote: "年龄一大，相信的东西就越来越少。和牙齿磨损一个样。既非玩世不恭，又不是疑神疑鬼，只是磨损而已。",
      source: "村上春树（Haruki Murakami）",
      type: "人生哲理",
      concept: "岁月对信仰的无声消磨",
      interpretation: "以牙齿磨损比喻人到中年信仰的渐次削减——这不是主动选择，而是被岁月无声打磨的结果。村上以极平常的生理现象解释了极深刻的心理变化，又准确又温柔。",
      alsoUse: "中年危机、人生反思、心理健康、价值观讨论",
      lang: "中文译",
      date: "2026-06-01",
    },
    {
      quote: "风是透明的河流，雨是冰凉的流星。",
      source: "李娟，中国当代作家",
      type: "自然宇宙",
      concept: "自然的诗意重塑",
      interpretation: "将无形的风比作“透明的河流”，将降落的雨比作“冰凉的流星”——两个意象均将日常天气现象转化为宇宙尺度的体验。李娟的文字有种天然的诗意，让人感觉大自然不是被观察的，而是被重新发明的。",
      alsoUse: "自然写作教学、诗歌创作、环保叙事、童年想象力培养",
      lang: "中文",
      date: "2026-06-01",
    },
    {
      quote: "理解并不是相似尺寸的经历和感情的叠加，而是穿上不同尺寸的衣服之后，重新检查自己身体的过程。",
      source: "金爱烂（韩国作家）",
      type: "人际情感",
      concept: "共情的本质",
      interpretation: "以“穿上不同尺寸的衣服”比喻理解他人——你不需要和对方有相同的经历，你需要的是进入对方的处境后重新审视自己。这个类比将“共情”从“感同身受”的常见误解中解放出来，指向了更深层的自我反思。",
      alsoUse: "共情教育、跨文化沟通、亲子关系、心理咨询",
      lang: "中文译",
      date: "2026-06-01",
    },
    {
      quote: "从优秀到卓越的转变从来不是一蹴而就的。它就像推动一个巨大的飞轮——你一圈一圈地推，每一圈都不会白费，最终在某一个突破点，飞轮产生了自己的动量。\nGood-to-great transformations never happen in one fell swoop. It’s like turning a giant, heavy flywheel—you push, and push, and push, until at some point, breakthrough happens.",
      source: "吉姆·柯林斯（Jim Collins），《从优秀到卓越》",
      type: "商业经济",
      concept: "持久努力的复利效应",
      interpretation: "以巨型飞轮的推动过程比喻组织转型——初期每一圈都异常艰难，但每一圈都在储能，直到跨过临界点后飞轮自己飞转。这个类比可视化了“量变引发质变”的商业逻辑，是管理学中最具影响力的比喻之一。",
      alsoUse: "企业转型、创业成长、个人习惯养成、产品迭代",
      lang: "EN/ZH",
      date: "2026-06-01",
    },
    {
      quote: "效率是以正确的方式做事，效能是做正确的事。\nEfficiency is doing things right; effectiveness is doing the right things.",
      source: "彼得·德鲁克（Peter Drucker），《卓有成效的管理者》",
      type: "治理管理",
      concept: "效率与效能的区别",
      interpretation: "以“做事的方式”和“做什么事”的对比，用最简单的语言揭示了管理学最核心的分野：你可以用极高的效率爬梯子，但如果梯子靠在错误的墙上，每一步都只会让你更快地到达错误的地方。",
      alsoUse: "战略规划、个人目标管理、时间管理、团队领导力",
      lang: "EN/ZH",
      date: "2026-06-01",
    },


    {
      quote: "他想着的那点事，像块化透了的鳔胶，把他的心整个儿糊满了；不但没有给外面的东西留个钻得进去的小缝儿，连他身上筋肉的一切动作，也没受他的心的指挥。",
      source: "老舍",
      type: "文学艺术",
      concept: "心事对人的吞噬性占据",
      interpretation: "以「鳔胶」的黏稠质地比喻心事全方位的压力——不仅封闭感知，连身体都不再听从指挥，超越了心理层面进入生理层面",
      alsoUse: "心理健康科普、焦虑症描述、人物形象塑造",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "我所谓的‘清香’，即食时如坐在河边闻到的新涨的春水的味道。",
      source: "汪曾祺",
      type: "文学艺术",
      concept: "食物清香的不可言传",
      interpretation: "将味觉比喻为河边静坐时闻到的春水气息，跳脱传统形容词，直接用情景机制转化味觉记忆",
      alsoUse: "美食评论、感官写作、体验设计",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "童年的朋友，犹如童年的衣裳，长大后，不是不愿意穿，是无可奈何了。",
      source: "木心",
      type: "人生哲理",
      concept: "时间对人际关系的改变",
      interpretation: "以童年衣裳不再合身比喻儿时友谊的渐行渐远，「无可奈何」四字抵得上千言万语——这是各自成长带来的自然疏离，无关谁对谁错",
      alsoUse: "老同学聚会、人际关系变迁、岁月感悟",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "心脏是一座有两间卧室的房子。一间住着痛苦，另一间住着欢乐。人不能笑得太响，否则笑声会吵醒隔壁房间的痛苦。",
      source: "卡夫卡（Franz Kafka）",
      type: "哲学思辨",
      concept: "人性中苦乐的共存与张力",
      interpretation: "以房子内部的卧室分隔比喻心理结构，而「笑声吵醒痛苦」这一细节将比喻升华为警示：人不能忘乎所以地快乐——苦乐永远毗邻而居",
      alsoUse: "情绪管理、悲观主义讨论、心理学普及",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "烦恼就像默不作声的蜘蛛，在暗地拉丝结网，爬过她的心的每个角落。",
      source: "福楼拜（Gustave Flaubert）",
      type: "文学艺术",
      concept: "烦恼的无声蔓延",
      interpretation: "以蜘蛛在暗处结网比喻烦恼的渐进性——它不是暴风骤雨，而是无声无息地占据每一寸心灵空间，等你发现时已网之过半",
      alsoUse: "情绪诊断、心理咨询、日常压力描述",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "如果问我思念多重，不重的，像一座秋山的落叶。",
      source: "简嫕，台湾作家",
      type: "人际情感",
      concept: "思念的沉重与轻盈的悖论",
      interpretation: "以整座秋山的落叶比喻思念——表面说「不重」，但秋山落叶合起来正是轧压般的重量；这种反说法让情感的密度更加沉甸甸",
      alsoUse: "情书写作、离别主题、情感表达",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "像每一滴酒回不了最初的葡萄，我回不到年少。",
      source: "简嫕，台湾作家",
      type: "人生哲理",
      concept: "时间不可逆的恸悔感",
      interpretation: "葡萄变酒是不可逆的发酵过程，用这个化学级的精确比喻来表达「再也回不去」的人生感悟，比直接叹息更有质感",
      alsoUse: "青春回忆、人生规划、后悔与成长",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "我仍搅着杯子，也许漂流久了的心情，就和离了岸的海水一般，若非遇到大风是不会翻起的。",
      source: "萧红",
      type: "人生哲理",
      concept: "風霜过后的内心平静",
      interpretation: "以离岸的海水比喻经历颠沛后的内心——静水深流，不再轻易被撼动，这种平静不是缺乏深度，而是深度过于沉重而难以波动",
      alsoUse: "职场历练、情感治愈、人格成熟",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "翠翠在风日里长养着，把皮肤变得黑黑的，触目为青山绿水，一对眸子清明如水晶。自然既长养她且教育她，为人天真活泼，处处俨然如一只小兽物。",
      source: "沈从文《边城》",
      type: "文学艺术",
      concept: "天真活泼的纯粹之美",
      interpretation: "以「小兽物」比喻未经文明雕琢的天真活泼，没有贬义，反而充满敕畏——那是大自然的作品，与山水同质",
      alsoUse: "人物塑造、少数民族文化、纯真气质描写",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "宇宙中恒星的总数，比地球上所有沙滩上的沙粒总数还要多。\nThe total number of stars in the universe is greater than all the grains of sand on all the beaches of the planet Earth.",
      source: "卡尔·萨根（Carl Sagan），《宇宙》（Cosmos）",
      type: "自然宇宙",
      concept: "宇宙的浩翰无垠",
      interpretation: "以人人都见过的沙滩沙粒为参照系，将抽象的宇宙尺度转化为可触摸的感知——你手捧一把沙，其数量已超过夜空所能见的所有星星",
      alsoUse: "天文科普、宇宙观教育、谦卑感培养",
      lang: "EN/ZH",
      date: "2026-06-03",
    },
    {
      quote: "所有模型都是错的，但有些模型是有用的。\nEssentially, all models are wrong, but some are useful.",
      source: "乔治·博克斯（George E. P. Box），统计学家",
      type: "科技创新",
      concept: "模型思维的本质与边界",
      interpretation: "以「错」「有用」这一矛盾组合比喻所有理论模型的本质：它们都是简化，因而都不完全精确；但判断标准不是精确，而是实用",
      alsoUse: "科研方法论、AI模型评估、策略规划",
      lang: "EN/ZH",
      date: "2026-06-03",
    },
    {
      quote: "你走了，这座城市就是拔掉牙齿的牙床，舔时痛，不舔时空荡。你归来时，又如新镶的假牙，忑忑陌生，好久才能亲近。",
      source: "佚名",
      type: "人际情感",
      concept: "离别的身体化记忆",
      interpretation: "以牙床缺失感比喻爱人离去后的空洞——舔也痛、不舔也空，这种身体化的痛感比任何心理描述都更直接；而「假牙」意象又暗示重逢后的陌生感——它在那里，但不是原来的那个他了",
      alsoUse: "失恋疗愈、移民情感、离别主题写作",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "对妈妈来说，整个世界就像一条没缝好的棉被，棉絮总是会露出来。而她的担心就像针一样，要把那些可怕的裂缝一一缝起来。",
      source: "罗伯特·麦卡蒙（Robert McCammon），《奇风岁月》",
      type: "人际情感",
      concept: "母爱的保护本能",
      interpretation: "以缝被子的动作比喻母亲对世界危险的接纳——棉絮是每个孩子面临的潜在风险，针线是母亲无处不在的操心，这个比喻温暖而不幼稚",
      alsoUse: "母亲节写作、家庭教育、亲子关系描述",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "在组织内部创造一个「安全圈」，就像父母为孩子提供安全的成长环境一样——这是领导者的第一责任。",
      source: "西蒙·斯涅克（Simon Sinek），《领导者最后吃》",
      type: "治理管理",
      concept: "领导力的核心是提供安全感",
      interpretation: "将领导者与团队的关系比作父母与孩子的关系，将抽象的「信任」「忠诚」转化为具体的「安全感」——团队的创造力取决于他们是否觉得安全",
      alsoUse: "企业文化建设、团队管理、心理安全感培训",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "一个老人辞世了，就像一座图书馆被烧毁了。",
      source: "贝纳尔·韦尔贝（Bernard Werber），法国作家",
      type: "教育学习",
      concept: "口述历史与人类智慧的流失",
      interpretation: "以图书馆被烧毁比喻老人辞世——每一个老人都是一座活的图书馆，储存着一生的经历、知识、故事，一旦离世，这些不可复制的智慧就永远消失了",
      alsoUse: "口述历史保护、家族故事传承、老龄化社会反思",
      lang: "中文",
      date: "2026-06-03",
    },


    {
      quote: "心里一阵嫉妒，像火上烤的栗子，热极要迸破了壳。",
      source: "钱锺书",
      type: "文学艺术",
      concept: "嫉妒心理",
      interpretation: "以火上烤栗子“热极迸壳”来比喻嫉妒心在胸中燃烧、随时爆发的强烈感，触觉、听觉、动态兼备",
      alsoUse: "意外惊喜、压抑不住的情绪、礁射内卷",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "人的命就像这琴弦，拉紧了才能弹好，弹好了就够了。",
      source: "史铁生《命若琴弦》",
      type: "人生哲理",
      concept: "命运与张力",
      interpretation: "用琴弦“拉紧”的张力来比喻人生需要压力与挑战——松弛的琴弦无法发声，弹好了就足够，不必追求完美结局",
      alsoUse: "抗压教育、工作与生活平衡、“略微有点紧”的生活智慧",
      lang: "中文",
      date: "2026-06-03",
    },
    {
      quote: "宇宙像一个保险箱，上面有密码，但密码锁在保险箱里面。
The universe is like a safe to which there is a combination. But the combination is locked up in the safe.",
      source: "彼得·德·弗里斯（Peter De Vries），美国小说家",
      type: "哲学思辨",
      concept: "终极答案的不可及性",
      interpretation: "将宇宙比作保险箱，而密码锁在里面——精妙地表达了生命终极答案的芭论性：我们在寻找的答案正是无法触及的东西",
      alsoUse: "认知边界、人工智能对齐问题、繁杂问题的“元问题”",
      lang: "英文译",
      date: "2026-06-03",
    },
    {
      quote: "一个期待处女作就能引起巨大反响的作者，就像一个人在大峡谷丢下一片玫瑰花瓣，然后等着听回声。
It has been well said that an author who expects results from a first novel is in a position similar to that of a man who drops a rose petal down the Grand Canyon of Arizona and listens for the echo.",
      source: "P.G. 沃德豪斯（P.G. Wodehouse），英国小说家",
      type: "文学艺术",
      concept: "初创作与现实期待",
      interpretation: "将处女作者期待巨大回响比作在大峡谷丢玫瑰花瓣等回声——一个形象到荒唐的比喻，说明初次创作想引起轰动是多么不切实际",
      alsoUse: "创业初期期待管理、新产品上市、职场新人心态",
      lang: "英文译",
      date: "2026-06-03",
    },
    {
      quote: "担忧就像试图用嘈泡泡糖来解代数方程。
Worrying is as effective as trying to solve an algebra equation by chewing bubble gum.",
      source: "巴兹·鲁赫曼（Baz Luhrmann），导演/作家（出自《全民防晒霜》）",
      type: "人生哲理",
      concept: "焦虑的无用性",
      interpretation: "将担忧比作用嘈泡泡糖解代数题——两者在本质上毫不相关，干躇且无效，精辟地点出焦虑对解决问题毫无帮助",
      alsoUse: "职场内耗、学习焦虑、情绪管理、内心平静练习",
      lang: "英文译",
      date: "2026-06-03",
    },
];
